services:
  # redis:
  #   image: redis/redis-stack:latest
  #   container_name: redis
  #   ports:
  #     - "6379:6379"
  #     - "8001:8001"

  postgres:
    image: postgres:16
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "postgres"]
      interval: 10s
      timeout: 10s
      retries: 3
  
  hyperbloom:
    image: gopds/hyperbloom:1.0
    container_name: hyperbloom
    depends_on:
      postgres:
        condition: service_healthy
    build:
      context: hyperbloom
    ports:
      - "5000:5000"
